from __future__ import annotations


ROLE_REPRESENTATION = "representation"
ROLE_INPUT_PARSING = "input_parsing"
ROLE_VALIDATION_CHECKING = "validation_checking"
ROLE_DIAGNOSTICS = "diagnostics"
ROLE_BEHAVIOR_OUTPUT = "behavior_output"
ROLE_TESTS = "tests"
ROLE_DOCS = "docs"
ROLE_CONFIG = "config"

INTENT_DEFECT_LOCALIZATION = "defect_localization"
INTENT_API_OR_USAGE_LOOKUP = "api_or_usage_lookup"
INTENT_BEHAVIOR_EXPLANATION = "behavior_explanation"
INTENT_CHANGE_OR_IMPACT_PLANNING = "change_or_impact_planning"
INTENT_REPOSITORY_EXPLORATION = "repository_exploration"
INTENT_CONFIGURATION_RUNTIME = "configuration_runtime"
INTENT_VERIFICATION_ANALYSIS = "verification_analysis"

ALL_RETRIEVAL_INTENTS = (
    INTENT_DEFECT_LOCALIZATION,
    INTENT_API_OR_USAGE_LOOKUP,
    INTENT_BEHAVIOR_EXPLANATION,
    INTENT_CHANGE_OR_IMPACT_PLANNING,
    INTENT_REPOSITORY_EXPLORATION,
    INTENT_CONFIGURATION_RUNTIME,
    INTENT_VERIFICATION_ANALYSIS,
)

SPECIFICITY_NARROW = "narrow"
SPECIFICITY_MEDIUM = "medium"
SPECIFICITY_BROAD = "broad"

ALL_RETRIEVAL_SPECIFICITIES = (
    SPECIFICITY_NARROW,
    SPECIFICITY_MEDIUM,
    SPECIFICITY_BROAD,
)

OBJECTIVE_IMPLEMENTATION_OWNER = "implementation_owner"
OBJECTIVE_INTERFACE_ENTRY = "interface_entry"
OBJECTIVE_BEHAVIOR_PATH = "behavior_path"
OBJECTIVE_DATA_STATE = "data_state"
OBJECTIVE_CONSTRAINTS_VALIDATION = "constraints_validation"
OBJECTIVE_EFFECTS_OUTPUT = "effects_output"
OBJECTIVE_DIAGNOSTIC_SURFACE = "diagnostic_surface"
OBJECTIVE_VERIFICATION_REPRO = "verification_repro"
OBJECTIVE_CONFIGURATION_CONTEXT = "configuration_context"
OBJECTIVE_USAGE_CONTRACT = "usage_contract"
OBJECTIVE_EXAMPLE_USAGE = "example_usage"
OBJECTIVE_DEPENDENT_CALLERS = "dependent_callers"
OBJECTIVE_SUBSYSTEM_OWNER = "subsystem_owner"
OBJECTIVE_DEPENDENCY_STRUCTURE = "dependency_structure"

ALL_RETRIEVAL_OBJECTIVES = (
    OBJECTIVE_IMPLEMENTATION_OWNER,
    OBJECTIVE_INTERFACE_ENTRY,
    OBJECTIVE_BEHAVIOR_PATH,
    OBJECTIVE_DATA_STATE,
    OBJECTIVE_CONSTRAINTS_VALIDATION,
    OBJECTIVE_EFFECTS_OUTPUT,
    OBJECTIVE_DIAGNOSTIC_SURFACE,
    OBJECTIVE_VERIFICATION_REPRO,
    OBJECTIVE_CONFIGURATION_CONTEXT,
    OBJECTIVE_USAGE_CONTRACT,
    OBJECTIVE_EXAMPLE_USAGE,
    OBJECTIVE_DEPENDENT_CALLERS,
    OBJECTIVE_SUBSYSTEM_OWNER,
    OBJECTIVE_DEPENDENCY_STRUCTURE,
)

DEFAULT_PRIMARY_INTENT = INTENT_BEHAVIOR_EXPLANATION
DEFAULT_SPECIFICITY = SPECIFICITY_MEDIUM

ALL_RETRIEVAL_ROLES = (
    ROLE_REPRESENTATION,
    ROLE_INPUT_PARSING,
    ROLE_VALIDATION_CHECKING,
    ROLE_DIAGNOSTICS,
    ROLE_BEHAVIOR_OUTPUT,
    ROLE_TESTS,
    ROLE_DOCS,
    ROLE_CONFIG,
)

DEFAULT_REQUIRED_RETRIEVAL_ROLES = (
    ROLE_REPRESENTATION,
    ROLE_INPUT_PARSING,
    ROLE_VALIDATION_CHECKING,
    ROLE_DIAGNOSTICS,
    ROLE_BEHAVIOR_OUTPUT,
)

DEFAULT_SUPPORTING_RETRIEVAL_ROLES = (
    ROLE_TESTS,
    ROLE_DOCS,
    ROLE_CONFIG,
)

DEFAULT_NEGATIVE_FILTERS = (
    "harness",
    "fixture",
    "baseline",
    "generated",
)

MAX_RAW_PROMPT_TERMS = 12
MAX_GROUNDED_ENTITIES = 12
MAX_GROUNDED_FILE_HINTS = 12
MAX_LLM_CONCEPT_TERMS = 10
MAX_LLM_SUBQUERIES = 8
MAX_RETRIEVAL_TERMS = 8
MAX_SPECULATIVE_ENTITIES = 8
MAX_NEGATIVE_FILTERS = 8
MAX_INITIAL_QUERY_COUNT = 10
MAX_GROUNDED_CGC_QUERIES = 4
