from __future__ import annotations


ROLE_REPRESENTATION = "representation"
ROLE_INPUT_PARSING = "input_parsing"
ROLE_VALIDATION_CHECKING = "validation_checking"
ROLE_DIAGNOSTICS = "diagnostics"
ROLE_BEHAVIOR_OUTPUT = "behavior_output"
ROLE_TESTS = "tests"
ROLE_DOCS = "docs"
ROLE_CONFIG = "config"

ALL_RETRIEVAL_ROLES = (
    ROLE_REPRESENTATION,
    ROLE_INPUT_PARSING,
    ROLE_VALIDATION_CHECKING,
    ROLE_DIAGNOSTICS,
    ROLE_BEHAVIOR_OUTPUT,
    ROLE_TESTS,
    ROLE_DOCS,
    ROLE_CONFIG,
)

DEFAULT_REQUIRED_RETRIEVAL_ROLES = (
    ROLE_REPRESENTATION,
    ROLE_INPUT_PARSING,
    ROLE_VALIDATION_CHECKING,
    ROLE_DIAGNOSTICS,
    ROLE_BEHAVIOR_OUTPUT,
)

DEFAULT_SUPPORTING_RETRIEVAL_ROLES = (
    ROLE_TESTS,
    ROLE_DOCS,
    ROLE_CONFIG,
)

DEFAULT_NEGATIVE_FILTERS = (
    "harness",
    "fixture",
    "baseline",
    "generated",
)

MAX_RAW_PROMPT_TERMS = 12
MAX_GROUNDED_ENTITIES = 12
MAX_GROUNDED_FILE_HINTS = 12
MAX_LLM_CONCEPT_TERMS = 10
MAX_LLM_SUBQUERIES = 8
MAX_RETRIEVAL_TERMS = 8
MAX_SPECULATIVE_ENTITIES = 8
MAX_NEGATIVE_FILTERS = 8
MAX_INITIAL_QUERY_COUNT = 10
MAX_GROUNDED_CGC_QUERIES = 4
