export const sourceLabels: Record<string, string> = {
  source_code: "Source code",
  repo_docs: "Repository docs",
  local_notes: "Local notes",
  notebooklm: "NotebookLM",
  github_issues: "GitHub issues",
  github_pull_requests: "GitHub PRs",
  notion: "Notion",
  shortcut: "Shortcut",
  jira: "Jira",
  confluence: "Confluence",
  linear: "Linear",
  slack: "Slack",
  google_drive: "Google Drive",
};

export const sourceOrder = [
  "source_code",
  "repo_docs",
  "local_notes",
  "notebooklm",
  "github_issues",
  "github_pull_requests",
  "notion",
  "shortcut",
  "jira",
  "confluence",
  "linear",
  "slack",
  "google_drive",
];
